name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install, lint, build 🔧
        run: |
          npm install
          npm run lint:js
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
      - name: 'Env'
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          REACT_APP_API_KEY: AIzaSyBHusGyGCOwMBFsuh17tAoev_9RQ6E_62U
